#!/usr/bin/env python
#
# Based on https://github.com/grundic/zabbix-disk-performance/blob/master/lld-disks.py

import json
import subprocess

if __name__ == '__main__':
    process = subprocess.Popen("awk '{print $3}' < /proc/diskstats | grep -v 'ram\|loop\|sr'", shell=True, stdout=subprocess.PIPE)
    output = process.communicate()[0]
    data = list()
    for line in output.split("\n"):
        if line:
	    device = line
	    devicename = line.replace("/dev/", "")
	    # display vg--lv instead of dm-x
	    if devicename.startswith("dm-"):
		process2 = subprocess.Popen("find /dev/mapper -type l -ls|grep -E '"+devicename+"$'|cut -d/ -f4|cut '-d ' -f1", shell=True, stdout=subprocess.PIPE)
		devicename = process2.communicate()[0].rstrip()
            data.append({"{#DEVICE}": device, "{#DEVICENAME}": devicename})

    print(json.dumps({"data": data}, indent=4))
